# Generated by Django 3.0.5 on 2020-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200501_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
    ]
