# Generated by Django 3.0.5 on 2020-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200501_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('datetime',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-datetime',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
