# Generated by Django 3.0.5 on 2020-05-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200502_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='website.Exercise'),
        ),
    ]
