# Generated by Django 3.0.5 on 2020-05-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20200502_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ('exercise__number', 'user__name')},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('exercise__number', 'user__name')},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='order',
            new_name='number',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=4096)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=256)),
                ('github', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(default=False)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.User'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='website.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='website.User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.User'),
        ),
    ]
