# Generated by Django 3.0.5 on 2020-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200502_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
