# Generated by Django 3.0.5 on 2020-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200502_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='directory',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
