# Generated by Django 3.0.5 on 2020-05-02 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_exercise_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='date',
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
